// Mocks generated by Mockito 5.4.2 from annotations
// in chatgpt_clone/test/providers/settings/settings_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:chatgpt_clone/services/chatgpt/openai_api_key_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OpenAIApiKeyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenAIApiKeyService extends _i1.Mock
    implements _i2.OpenAIApiKeyService {
  @override
  _i3.Future<void> storeApiKey(String? apiKey) => (super.noSuchMethod(
        Invocation.method(
          #storeApiKey,
          [apiKey],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<String?> provideApiKey() => (super.noSuchMethod(
        Invocation.method(
          #provideApiKey,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
        returnValueForMissingStub: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
  @override
  _i3.Future<void> deleteApiKey() => (super.noSuchMethod(
        Invocation.method(
          #deleteApiKey,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
